name: Hugo Build and Deploy

# 触发条件：当有内容推送到仓库时，尤其是 Markdown 文件有更新
on:
  push:
    paths:
      - 'content/**/*.md'  # 仅当 content 目录下的 Markdown 文件有更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版的运行环境

    steps:
      # 步骤 1: 检出代码到运行环境
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # 拉取 Hugo 主题等子模块
          fetch-depth: 0    # 获取完整的提交历史

      # 步骤 2: 设置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 使用最新版本的 Hugo
          extended: true          # 使用扩展版本的 Hugo

      # 步骤 3: 构建 Hugo 网站
      - name: Build
        run: hugo --minify

      # 步骤 5: 克隆目标仓库
      - name: Clone Destination Repository
        run: git clone https://github.com/LACS-Official/app-website.git app-website-clone

      # 步骤 6: 清空目标仓库内容
      - name: Clear Destination Repository
        run: rm -rf app-website-clone/*

      # 步骤 7: 复制构建好的文件到目标仓库
      - name: Copy Build Files
        run: cp -r public/* app-website-clone/

      # 步骤 8: 提交并推送更改到目标仓库
      - name: Commit and Push
        working-directory: app-website-clone
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Deploy Hugo site"
          git push https://${{ secrets.DEPLOY_TOKEN }}@github.com/LACS-Official/app-website.git